# Generated by Django 5.1.1 on 2024-09-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='moderated',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('analyze', 'Анализирует нейросеть'), ('moderation', 'На модерации'), ('published', 'Опубликован')], default='analyze', max_length=20),
        ),
    ]
